version: '3.1'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    networks:
      - comm_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  store:
    image: store
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: store
    networks:
      - comm_network
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017
    ports:
      - 5000:5000

networks:
  comm_network:
    name: mongodb
