version: '3.1'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  task-manager:
    image: task-manager
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: task-manager
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017
    ports:
      - 3000:3000
